# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c1a796c0187c92f3ac377837734ea583fd6b62ee25708d728f2c4d76a403ad13d74b5a7b96f00cdbb8591cd284f08c7690e148cd9a273aed7db62588f81a8cca

test:
  secret_key_base: 69c832a3a314e5a88def646c9d233ef7f87a5e5ee60250989eac267b621fed88ff07cdbc92a7fc925f397ec3956bd968a7f19a1b24236167b1a01e6cddbb9fc9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
